# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zeeshan/Desktop/garbled_circuit/consumer_data_privacy_gca

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zeeshan/Desktop/garbled_circuit/consumer_data_privacy_gca

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zeeshan/Desktop/garbled_circuit/consumer_data_privacy_gca/CMakeFiles /home/zeeshan/Desktop/garbled_circuit/consumer_data_privacy_gca/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zeeshan/Desktop/garbled_circuit/consumer_data_privacy_gca/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Frame_Match_24

# Build rule for target.
Frame_Match_24: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_24
.PHONY : Frame_Match_24

# fast build rule for target.
Frame_Match_24/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_24.dir/build.make CMakeFiles/Frame_Match_24.dir/build
.PHONY : Frame_Match_24/fast

#=============================================================================
# Target rules for targets named Frame_Match_104

# Build rule for target.
Frame_Match_104: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_104
.PHONY : Frame_Match_104

# fast build rule for target.
Frame_Match_104/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_104.dir/build.make CMakeFiles/Frame_Match_104.dir/build
.PHONY : Frame_Match_104/fast

#=============================================================================
# Target rules for targets named Frame_Match_54

# Build rule for target.
Frame_Match_54: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_54
.PHONY : Frame_Match_54

# fast build rule for target.
Frame_Match_54/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_54.dir/build.make CMakeFiles/Frame_Match_54.dir/build
.PHONY : Frame_Match_54/fast

#=============================================================================
# Target rules for targets named Frame_Match_16

# Build rule for target.
Frame_Match_16: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_16
.PHONY : Frame_Match_16

# fast build rule for target.
Frame_Match_16/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_16.dir/build.make CMakeFiles/Frame_Match_16.dir/build
.PHONY : Frame_Match_16/fast

#=============================================================================
# Target rules for targets named Frame_Match_128

# Build rule for target.
Frame_Match_128: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_128
.PHONY : Frame_Match_128

# fast build rule for target.
Frame_Match_128/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_128.dir/build.make CMakeFiles/Frame_Match_128.dir/build
.PHONY : Frame_Match_128/fast

#=============================================================================
# Target rules for targets named Frame_Match

# Build rule for target.
Frame_Match: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match
.PHONY : Frame_Match

# fast build rule for target.
Frame_Match/fast:
	$(MAKE) -f CMakeFiles/Frame_Match.dir/build.make CMakeFiles/Frame_Match.dir/build
.PHONY : Frame_Match/fast

#=============================================================================
# Target rules for targets named Frame_Match_64

# Build rule for target.
Frame_Match_64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_64
.PHONY : Frame_Match_64

# fast build rule for target.
Frame_Match_64/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_64.dir/build.make CMakeFiles/Frame_Match_64.dir/build
.PHONY : Frame_Match_64/fast

#=============================================================================
# Target rules for targets named Frame_Match_1

# Build rule for target.
Frame_Match_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_1
.PHONY : Frame_Match_1

# fast build rule for target.
Frame_Match_1/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_1.dir/build.make CMakeFiles/Frame_Match_1.dir/build
.PHONY : Frame_Match_1/fast

#=============================================================================
# Target rules for targets named Frame_Match_4

# Build rule for target.
Frame_Match_4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frame_Match_4
.PHONY : Frame_Match_4

# fast build rule for target.
Frame_Match_4/fast:
	$(MAKE) -f CMakeFiles/Frame_Match_4.dir/build.make CMakeFiles/Frame_Match_4.dir/build
.PHONY : Frame_Match_4/fast

test/Frame_Match.o: test/Frame_Match.cpp.o

.PHONY : test/Frame_Match.o

# target to build an object file
test/Frame_Match.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match.dir/build.make CMakeFiles/Frame_Match.dir/test/Frame_Match.cpp.o
.PHONY : test/Frame_Match.cpp.o

test/Frame_Match.i: test/Frame_Match.cpp.i

.PHONY : test/Frame_Match.i

# target to preprocess a source file
test/Frame_Match.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match.dir/build.make CMakeFiles/Frame_Match.dir/test/Frame_Match.cpp.i
.PHONY : test/Frame_Match.cpp.i

test/Frame_Match.s: test/Frame_Match.cpp.s

.PHONY : test/Frame_Match.s

# target to generate assembly for a file
test/Frame_Match.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match.dir/build.make CMakeFiles/Frame_Match.dir/test/Frame_Match.cpp.s
.PHONY : test/Frame_Match.cpp.s

test/Frame_Match_1.o: test/Frame_Match_1.cpp.o

.PHONY : test/Frame_Match_1.o

# target to build an object file
test/Frame_Match_1.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_1.dir/build.make CMakeFiles/Frame_Match_1.dir/test/Frame_Match_1.cpp.o
.PHONY : test/Frame_Match_1.cpp.o

test/Frame_Match_1.i: test/Frame_Match_1.cpp.i

.PHONY : test/Frame_Match_1.i

# target to preprocess a source file
test/Frame_Match_1.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_1.dir/build.make CMakeFiles/Frame_Match_1.dir/test/Frame_Match_1.cpp.i
.PHONY : test/Frame_Match_1.cpp.i

test/Frame_Match_1.s: test/Frame_Match_1.cpp.s

.PHONY : test/Frame_Match_1.s

# target to generate assembly for a file
test/Frame_Match_1.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_1.dir/build.make CMakeFiles/Frame_Match_1.dir/test/Frame_Match_1.cpp.s
.PHONY : test/Frame_Match_1.cpp.s

test/Frame_Match_104.o: test/Frame_Match_104.cpp.o

.PHONY : test/Frame_Match_104.o

# target to build an object file
test/Frame_Match_104.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_104.dir/build.make CMakeFiles/Frame_Match_104.dir/test/Frame_Match_104.cpp.o
.PHONY : test/Frame_Match_104.cpp.o

test/Frame_Match_104.i: test/Frame_Match_104.cpp.i

.PHONY : test/Frame_Match_104.i

# target to preprocess a source file
test/Frame_Match_104.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_104.dir/build.make CMakeFiles/Frame_Match_104.dir/test/Frame_Match_104.cpp.i
.PHONY : test/Frame_Match_104.cpp.i

test/Frame_Match_104.s: test/Frame_Match_104.cpp.s

.PHONY : test/Frame_Match_104.s

# target to generate assembly for a file
test/Frame_Match_104.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_104.dir/build.make CMakeFiles/Frame_Match_104.dir/test/Frame_Match_104.cpp.s
.PHONY : test/Frame_Match_104.cpp.s

test/Frame_Match_128.o: test/Frame_Match_128.cpp.o

.PHONY : test/Frame_Match_128.o

# target to build an object file
test/Frame_Match_128.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_128.dir/build.make CMakeFiles/Frame_Match_128.dir/test/Frame_Match_128.cpp.o
.PHONY : test/Frame_Match_128.cpp.o

test/Frame_Match_128.i: test/Frame_Match_128.cpp.i

.PHONY : test/Frame_Match_128.i

# target to preprocess a source file
test/Frame_Match_128.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_128.dir/build.make CMakeFiles/Frame_Match_128.dir/test/Frame_Match_128.cpp.i
.PHONY : test/Frame_Match_128.cpp.i

test/Frame_Match_128.s: test/Frame_Match_128.cpp.s

.PHONY : test/Frame_Match_128.s

# target to generate assembly for a file
test/Frame_Match_128.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_128.dir/build.make CMakeFiles/Frame_Match_128.dir/test/Frame_Match_128.cpp.s
.PHONY : test/Frame_Match_128.cpp.s

test/Frame_Match_16.o: test/Frame_Match_16.cpp.o

.PHONY : test/Frame_Match_16.o

# target to build an object file
test/Frame_Match_16.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_16.dir/build.make CMakeFiles/Frame_Match_16.dir/test/Frame_Match_16.cpp.o
.PHONY : test/Frame_Match_16.cpp.o

test/Frame_Match_16.i: test/Frame_Match_16.cpp.i

.PHONY : test/Frame_Match_16.i

# target to preprocess a source file
test/Frame_Match_16.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_16.dir/build.make CMakeFiles/Frame_Match_16.dir/test/Frame_Match_16.cpp.i
.PHONY : test/Frame_Match_16.cpp.i

test/Frame_Match_16.s: test/Frame_Match_16.cpp.s

.PHONY : test/Frame_Match_16.s

# target to generate assembly for a file
test/Frame_Match_16.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_16.dir/build.make CMakeFiles/Frame_Match_16.dir/test/Frame_Match_16.cpp.s
.PHONY : test/Frame_Match_16.cpp.s

test/Frame_Match_24.o: test/Frame_Match_24.cpp.o

.PHONY : test/Frame_Match_24.o

# target to build an object file
test/Frame_Match_24.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_24.dir/build.make CMakeFiles/Frame_Match_24.dir/test/Frame_Match_24.cpp.o
.PHONY : test/Frame_Match_24.cpp.o

test/Frame_Match_24.i: test/Frame_Match_24.cpp.i

.PHONY : test/Frame_Match_24.i

# target to preprocess a source file
test/Frame_Match_24.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_24.dir/build.make CMakeFiles/Frame_Match_24.dir/test/Frame_Match_24.cpp.i
.PHONY : test/Frame_Match_24.cpp.i

test/Frame_Match_24.s: test/Frame_Match_24.cpp.s

.PHONY : test/Frame_Match_24.s

# target to generate assembly for a file
test/Frame_Match_24.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_24.dir/build.make CMakeFiles/Frame_Match_24.dir/test/Frame_Match_24.cpp.s
.PHONY : test/Frame_Match_24.cpp.s

test/Frame_Match_4.o: test/Frame_Match_4.cpp.o

.PHONY : test/Frame_Match_4.o

# target to build an object file
test/Frame_Match_4.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_4.dir/build.make CMakeFiles/Frame_Match_4.dir/test/Frame_Match_4.cpp.o
.PHONY : test/Frame_Match_4.cpp.o

test/Frame_Match_4.i: test/Frame_Match_4.cpp.i

.PHONY : test/Frame_Match_4.i

# target to preprocess a source file
test/Frame_Match_4.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_4.dir/build.make CMakeFiles/Frame_Match_4.dir/test/Frame_Match_4.cpp.i
.PHONY : test/Frame_Match_4.cpp.i

test/Frame_Match_4.s: test/Frame_Match_4.cpp.s

.PHONY : test/Frame_Match_4.s

# target to generate assembly for a file
test/Frame_Match_4.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_4.dir/build.make CMakeFiles/Frame_Match_4.dir/test/Frame_Match_4.cpp.s
.PHONY : test/Frame_Match_4.cpp.s

test/Frame_Match_54.o: test/Frame_Match_54.cpp.o

.PHONY : test/Frame_Match_54.o

# target to build an object file
test/Frame_Match_54.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_54.dir/build.make CMakeFiles/Frame_Match_54.dir/test/Frame_Match_54.cpp.o
.PHONY : test/Frame_Match_54.cpp.o

test/Frame_Match_54.i: test/Frame_Match_54.cpp.i

.PHONY : test/Frame_Match_54.i

# target to preprocess a source file
test/Frame_Match_54.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_54.dir/build.make CMakeFiles/Frame_Match_54.dir/test/Frame_Match_54.cpp.i
.PHONY : test/Frame_Match_54.cpp.i

test/Frame_Match_54.s: test/Frame_Match_54.cpp.s

.PHONY : test/Frame_Match_54.s

# target to generate assembly for a file
test/Frame_Match_54.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_54.dir/build.make CMakeFiles/Frame_Match_54.dir/test/Frame_Match_54.cpp.s
.PHONY : test/Frame_Match_54.cpp.s

test/Frame_Match_64.o: test/Frame_Match_64.cpp.o

.PHONY : test/Frame_Match_64.o

# target to build an object file
test/Frame_Match_64.cpp.o:
	$(MAKE) -f CMakeFiles/Frame_Match_64.dir/build.make CMakeFiles/Frame_Match_64.dir/test/Frame_Match_64.cpp.o
.PHONY : test/Frame_Match_64.cpp.o

test/Frame_Match_64.i: test/Frame_Match_64.cpp.i

.PHONY : test/Frame_Match_64.i

# target to preprocess a source file
test/Frame_Match_64.cpp.i:
	$(MAKE) -f CMakeFiles/Frame_Match_64.dir/build.make CMakeFiles/Frame_Match_64.dir/test/Frame_Match_64.cpp.i
.PHONY : test/Frame_Match_64.cpp.i

test/Frame_Match_64.s: test/Frame_Match_64.cpp.s

.PHONY : test/Frame_Match_64.s

# target to generate assembly for a file
test/Frame_Match_64.cpp.s:
	$(MAKE) -f CMakeFiles/Frame_Match_64.dir/build.make CMakeFiles/Frame_Match_64.dir/test/Frame_Match_64.cpp.s
.PHONY : test/Frame_Match_64.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Frame_Match_24"
	@echo "... Frame_Match_104"
	@echo "... Frame_Match_54"
	@echo "... install/local"
	@echo "... Frame_Match_16"
	@echo "... Frame_Match_128"
	@echo "... Frame_Match"
	@echo "... Frame_Match_64"
	@echo "... install/strip"
	@echo "... Frame_Match_1"
	@echo "... list_install_components"
	@echo "... Frame_Match_4"
	@echo "... test/Frame_Match.o"
	@echo "... test/Frame_Match.i"
	@echo "... test/Frame_Match.s"
	@echo "... test/Frame_Match_1.o"
	@echo "... test/Frame_Match_1.i"
	@echo "... test/Frame_Match_1.s"
	@echo "... test/Frame_Match_104.o"
	@echo "... test/Frame_Match_104.i"
	@echo "... test/Frame_Match_104.s"
	@echo "... test/Frame_Match_128.o"
	@echo "... test/Frame_Match_128.i"
	@echo "... test/Frame_Match_128.s"
	@echo "... test/Frame_Match_16.o"
	@echo "... test/Frame_Match_16.i"
	@echo "... test/Frame_Match_16.s"
	@echo "... test/Frame_Match_24.o"
	@echo "... test/Frame_Match_24.i"
	@echo "... test/Frame_Match_24.s"
	@echo "... test/Frame_Match_4.o"
	@echo "... test/Frame_Match_4.i"
	@echo "... test/Frame_Match_4.s"
	@echo "... test/Frame_Match_54.o"
	@echo "... test/Frame_Match_54.i"
	@echo "... test/Frame_Match_54.s"
	@echo "... test/Frame_Match_64.o"
	@echo "... test/Frame_Match_64.i"
	@echo "... test/Frame_Match_64.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

